### ISSUE TITLE
Is asr task job can run correctly on gpu?

### ISSUE THREAD

**Issue by fanlu** [tensorflow/lingvo#11]
I use tf-nightly-gpu==1.13.0-dev20181116, but when I run asr task, I got the error below.
```
bazel-bin/lingvo/trainer --run_locally=gpu --mode=sync --model=asr.librispeech.Librispeech960Base --logdir=/tmp/librispeech/log --logtostderr
```
```
INFO:tensorflow:Retry: caught exception: _WaitTillInit while running FailedPreconditionError: Attempting to use uninitialized value global_step
	 [[{{node _send_global_step_0}}]]
. Call failed at (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 401, in Start
    self._RunLoop('trainer', self._Loop)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/retry.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/base_runner.py", line 173, in _RunLoop
    loop_func(*args)
Traceback for above exception (most recent call last):
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/retry.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 416, in _WaitTillInit
    global_step = sess.run(self._model.global_step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
Waiting for 0.11 seconds before retrying.
```

**Comment by drpngx** [comment]
Yes that's expected. Just wait until you see something like `Writing Summary@1` or something with `step:`.

**Comment by fanlu** [comment]
there is no summary and step output. and the training thread is exit.
this is the following error msg:
```
INFO:tensorflow:<b>Retrying as expected</b> trainer exception: FailedPreconditionError()

ERROR:tensorflow:Traceback (most recent call last):
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/base_runner.py", line 165, in _RunLoop
ERROR:tensorflow:    loop_func(*args)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 472, in _Loop
ERROR:tensorflow:    model_task.trainer_verbose_tensors,
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
ERROR:tensorflow:    run_metadata_ptr)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
ERROR:tensorflow:    feed_dict_tensor, options, run_metadata)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
ERROR:tensorflow:    run_metadata)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
ERROR:tensorflow:    raise type(e)(node_def, op, message)
ERROR:tensorflow:FailedPreconditionError: Attempting to use uninitialized value librispeech/dec/softmax/bias_0/var
ERROR:tensorflow:	 [[node librispeech/dec/softmax/bias_0/var/read (defined at /tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py:1003) ]]
ERROR:tensorflow:
ERROR:tensorflow:Caused by op u'librispeech/dec/softmax/bias_0/var/read', defined at:
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1284, in <module>
ERROR:tensorflow:    tf.app.run(main)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
ERROR:tensorflow:    _sys.exit(main(argv))
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1280, in main
ERROR:tensorflow:    RunnerManager(FLAGS.model).Start()
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1273, in Start
ERROR:tensorflow:    self.StartRunners(self.CreateRunners(FLAGS.job.split(','), FLAGS.logdir))
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1085, in CreateRunners
ERROR:tensorflow:    trial)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1048, in _CreateRunner
ERROR:tensorflow:    return self.Trainer(cfg, *common_args)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 367, in __init__
ERROR:tensorflow:    self._model = self.params.cls(self.params)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 118, in wrapper
ERROR:tensorflow:    func(self, *args, **kwargs)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 1083, in __init__
ERROR:tensorflow:    self.CreateChild('_task', p.task)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 576, in CreateChild
ERROR:tensorflow:    child = p.cls(p)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 118, in wrapper
ERROR:tensorflow:    func(self, *args, **kwargs)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/tasks/asr/model.py", line 89, in __init__
ERROR:tensorflow:    self.CreateChild('decoder', p.decoder)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 576, in CreateChild
ERROR:tensorflow:    child = p.cls(p)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 118, in wrapper
ERROR:tensorflow:    func(self, *args, **kwargs)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/tasks/asr/decoder.py", line 305, in __init__
ERROR:tensorflow:    self.CreateChild('softmax', p.softmax)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 576, in CreateChild
ERROR:tensorflow:    child = p.cls(p)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 118, in wrapper
ERROR:tensorflow:    func(self, *args, **kwargs)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 1945, in __init__
ERROR:tensorflow:    self.CreateVariable('bias_%d' % i, pc, self.AddGlobalVN)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 540, in CreateVariable
ERROR:tensorflow:    value, var = py_utils.CreateVariable(name, var_params, *args, **kwargs)
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py", line 1011, in CreateVariable
ERROR:tensorflow:    var = GetVar()
ERROR:tensorflow:  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py", line 1003, in GetVar
ERROR:tensorflow:    validate_shape=True if shape is not None else False)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1523, in get_variable
ERROR:tensorflow:    aggregation=aggregation)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1261, in get_variable
ERROR:tensorflow:    aggregation=aggregation)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 547, in get_variable
ERROR:tensorflow:    aggregation=aggregation)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 499, in _true_getter
ERROR:tensorflow:    aggregation=aggregation)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 946, in _get_single_variable
ERROR:tensorflow:    aggregation=aggregation)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 212, in __call__
ERROR:tensorflow:    return cls._variable_v1_call(*args, **kwargs)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 175, in _variable_v1_call
ERROR:tensorflow:    aggregation=aggregation)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 154, in <lambda>
ERROR:tensorflow:    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 2502, in default_variable_creator
ERROR:tensorflow:    expected_shape=expected_shape, import_scope=import_scope)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 216, in __call__
ERROR:tensorflow:    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 1358, in __init__
ERROR:tensorflow:    constraint=constraint)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 1520, in _init_from_args
ERROR:tensorflow:    self._snapshot = array_ops.identity(self._variable, name="read")
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 79, in identity
ERROR:tensorflow:    return gen_array_ops.identity(input, name=name)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3587, in identity
ERROR:tensorflow:    "Identity", input=input, name=name)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
ERROR:tensorflow:    op_def=op_def)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 512, in new_func
ERROR:tensorflow:    return func(*args, **kwargs)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3364, in create_op
ERROR:tensorflow:    op_def=op_def)
ERROR:tensorflow:  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1858, in __init__
ERROR:tensorflow:    self._traceback = tf_stack.extract_stack()
ERROR:tensorflow:
ERROR:tensorflow:FailedPreconditionError (see above for traceback): Attempting to use uninitialized value librispeech/dec/softmax/bias_0/var
ERROR:tensorflow:	 [[node librispeech/dec/softmax/bias_0/var/read (defined at /tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py:1003) ]]
ERROR:tensorflow:
ERROR:tensorflow:
INFO:tensorflow:Retry: caught exception: _RunLoop while running FailedPreconditionError: Attempting to use uninitialized value librispeech/dec/softmax/bias_0/var
	 [[node librispeech/dec/softmax/bias_0/var/read (defined at /tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py:1003) ]]

Caused by op u'librispeech/dec/softmax/bias_0/var/read', defined at:
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1284, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1280, in main
    RunnerManager(FLAGS.model).Start()
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1273, in Start
    self.StartRunners(self.CreateRunners(FLAGS.job.split(','), FLAGS.logdir))
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1085, in CreateRunners
    trial)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1048, in _CreateRunner
    return self.Trainer(cfg, *common_args)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 367, in __init__
    self._model = self.params.cls(self.params)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 118, in wrapper
    func(self, *args, **kwargs)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 1083, in __init__
    self.CreateChild('_task', p.task)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 576, in CreateChild
    child = p.cls(p)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 118, in wrapper
    func(self, *args, **kwargs)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/tasks/asr/model.py", line 89, in __init__
    self.CreateChild('decoder', p.decoder)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 576, in CreateChild
    child = p.cls(p)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 118, in wrapper
    func(self, *args, **kwargs)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/tasks/asr/decoder.py", line 305, in __init__
    self.CreateChild('softmax', p.softmax)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 576, in CreateChild
    child = p.cls(p)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 118, in wrapper
    func(self, *args, **kwargs)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 1945, in __init__
    self.CreateVariable('bias_%d' % i, pc, self.AddGlobalVN)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_layer.py", line 540, in CreateVariable
    value, var = py_utils.CreateVariable(name, var_params, *args, **kwargs)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py", line 1011, in CreateVariable
    var = GetVar()
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py", line 1003, in GetVar
    validate_shape=True if shape is not None else False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1523, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 1261, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 547, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 499, in _true_getter
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 946, in _get_single_variable
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 212, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 175, in _variable_v1_call
    aggregation=aggregation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 154, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variable_scope.py", line 2502, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 216, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 1358, in __init__
    constraint=constraint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 1520, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 79, in identity
    return gen_array_ops.identity(input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3587, in identity
    "Identity", input=input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 512, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3364, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1858, in __init__
    self._traceback = tf_stack.extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value librispeech/dec/softmax/bias_0/var
	 [[node librispeech/dec/softmax/bias_0/var/read (defined at /tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py:1003) ]]

. Call failed at (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
Traceback for above exception (most recent call last):
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/retry.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/base_runner.py", line 165, in _RunLoop
    loop_func(*args)
  File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 472, in _Loop
    model_task.trainer_verbose_tensors,
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
Waiting for 0.11 seconds before retrying.
INFO:tensorflow:trainer started.
```

**Comment by drpngx** [comment]
Can you run with `--enable_asserts=false` for now?

**Comment by fanlu** [comment]
It's worked when using --enable_asserts=false? but It's only use one gpu card.
Could you please add readme to asr task?

**Comment by fanlu** [comment]
this is the command I used.
```
bazel-bin/lingvo/trainer --run_locally=gpu --mode=sync --model=asr.librispeech.Librispeech960Base --logdir=/tmp/librispeech/log --logtostderr --enable_asserts=false
```
I found another problem, the loss does not decrease from start.
```
2018-11-20 04:24:40.685925: W ./lingvo/core/ops/tokenizer_op_headers.h:68] Too long target 301 JUST SITTING AND WATCHING WAS FRUSTRATING PARTICULARLY WHEN IT WAS A DESPERATE EMERGENCY HE DIDN'T OVERVALUE HIS WORTH BUT HE WAS SURE THERE WAS ALWAYS ROOM FOR ANOTHER GUN BY THE TIME HE HAD DRAGGED HIMSELF DOWN TO THE STREET LEVEL A TURBO TRUCK HAD SLAMMED TO A STOP IN FRONT OF THE LOADING PLATFORM
INFO:tensorflow:Steps/second: 0.090317, Examples/second: 4.592744
INFO:tensorflow:Write summary @101
INFO:tensorflow:step:   101 fraction_of_correct_next_step_preds:0.0065470417 fraction_of_correct_next_step_preds/logits:0.0065470417 log_pplx:4.9673233 log_pplx/logits:4.9673233 loss:4.9673233 loss/logits:4.9673233 num_samples_in_batch:48
INFO:tensorflow:step:   102 fraction_of_correct_next_step_preds:0.010749019 fraction_of_correct_next_step_preds/logits:0.010749019 log_pplx:4.9570217 log_pplx/logits:4.9570217 loss:4.9570217 loss/logits:4.9570217 num_samples_in_batch:48
INFO:tensorflow:step:   103 fraction_of_correct_next_step_preds:0.014047265 fraction_of_correct_next_step_preds/logits:0.014047265 log_pplx:4.9854736 log_pplx/logits:4.9854736 loss:4.9854736 loss/logits:4.9854736 num_samples_in_batch:96
INFO:tensorflow:step:   104 fraction_of_correct_next_step_preds:0.010524165 fraction_of_correct_next_step_preds/logits:0.010524165 log_pplx:4.9925981 log_pplx/logits:4.9925981 loss:4.9925981 loss/logits:4.9925981 num_samples_in_batch:48
INFO:tensorflow:step:   105 fraction_of_correct_next_step_preds:0.0068986509 fraction_of_correct_next_step_preds/logits:0.0068986509 log_pplx:5.0027204 log_pplx/logits:5.0027204 loss:5.0027204 loss/logits:5.0027204 num_samples_in_batch:48
INFO:tensorflow:step:   106 fraction_of_correct_next_step_preds:0.010397326 fraction_of_correct_next_step_preds/logits:0.010397326 log_pplx:4.9780407 log_pplx/logits:4.9780407 loss:4.9780407 loss/logits:4.9780407 num_samples_in_batch:48
INFO:tensorflow:Write summary done: step 101
INFO:tensorflow:step:   101, steps/sec: 0.09, examples/sec: 4.59
INFO:tensorflow:Steps/second: 0.089864, Examples/second: 4.595674
INFO:tensorflow:step:   107 fraction_of_correct_next_step_preds:0.010022573 fraction_of_correct_next_step_preds/logits:0.010022573 log_pplx:5.009697 log_pplx/logits:5.009697 loss:5.009697 loss/logits:5.009697 num_samples_in_batch:48
INFO:tensorflow:Steps/second: 0.089948, Examples/second: 4.597317
INFO:tensorflow:Save checkpoint
WARNING:tensorflow:Issue encountered when serializing __batch_norm_update_dict.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'dict' object has no attribute 'name'
WARNING:tensorflow:Issue encountered when serializing __model_split_id_stack.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'list' object has no attribute 'name'
INFO:tensorflow:Save checkpoint done: /tmp/librispeech/log/train/ckpt-00000108
INFO:tensorflow:step:   108 fraction_of_correct_next_step_preds:0.0051525962 fraction_of_correct_next_step_preds/logits:0.0051525962 log_pplx:4.9994984 log_pplx/logits:4.9994984 loss:4.9994984 loss/logits:4.9994984 num_samples_in_batch:48
INFO:tensorflow:Steps/second: 0.090030, Examples/second: 4.598981
INFO:tensorflow:step:   109 fraction_of_correct_next_step_preds:0.011224868 fraction_of_correct_next_step_preds/logits:0.011224868 log_pplx:4.9820132 log_pplx/logits:4.9820132 loss:4.9820132 loss/logits:4.9820132 num_samples_in_batch:48
INFO:tensorflow:Steps/second: 0.090111, Examples/second: 4.600591
INFO:tensorflow:step:   110 fraction_of_correct_next_step_preds:0.0067334538 fraction_of_correct_next_step_preds/logits:0.0067334538 log_pplx:5.0105591 log_pplx/logits:5.0105591 loss:5.0105591 loss/logits:5.0105591 num_samples_in_batch:48
INFO:tensorflow:Steps/second: 0.090191, Examples/second: 4.602178
INFO:tensorflow:step:   111 fraction_of_correct_next_step_preds:0.0084050633 fraction_of_correct_next_step_preds/logits:0.0084050633 log_pplx:4.9993515 log_pplx/logits:4.9993515 loss:4.9993515 loss/logits:4.9993515 num_samples_in_batch:48
INFO:tensorflow:Steps/second: 0.090269, Examples/second: 4.603743
INFO:tensorflow:step:   112 fraction_of_correct_next_step_preds:0.0077442196 fraction_of_correct_next_step_preds/logits:0.0077442196 log_pplx:4.9817152 log_pplx/logits:4.9817152 loss:4.9817152 loss/logits:4.9817152 num_samples_in_batch:48
```

**Comment by fanlu** [comment]
this is the command I used.
```
bazel-bin/lingvo/trainer --run_locally=gpu --mode=sync --model=asr.librispeech.Librispeech960Base --logdir=/tmp/librispeech/log --logtostderr --enable_asserts=false
```
I found another problem, the loss does not decrease from start.
```
2018-11-20 04:24:40.685925: W ./lingvo/core/ops/tokenizer_op_headers.h:68] Too long target 301 JUST SITTING AND WATCHING WAS FRUSTRATING PARTICULARLY WHEN IT WAS A DESPERATE EMERGENCY HE DIDN'T OVERVALUE HIS WORTH BUT HE WAS SURE THERE WAS ALWAYS ROOM FOR ANOTHER GUN BY THE TIME HE HAD DRAGGED HIMSELF DOWN TO THE STREET LEVEL A TURBO TRUCK HAD SLAMMED TO A STOP IN FRONT OF THE LOADING PLATFORM
INFO:tensorflow:Steps/second: 0.090317, Examples/second: 4.592744
INFO:tensorflow:Write summary @101
INFO:tensorflow:step:   101 fraction_of_correct_next_step_preds:0.0065470417 fraction_of_correct_next_step_preds/logits:0.0065470417 log_pplx:4.9673233 log_pplx/logits:4.9673233 loss:4.9673233 loss/logits:4.9673233 num_samples_in_batch:48
INFO:tensorflow:step:   102 fraction_of_correct_next_step_preds:0.010749019 fraction_of_correct_next_step_preds/logits:0.010749019 log_pplx:4.9570217 log_pplx/logits:4.9570217 loss:4.9570217 loss/logits:4.9570217 num_samples_in_batch:48
INFO:tensorflow:step:   103 fraction_of_correct_next_step_preds:0.014047265 fraction_of_correct_next_step_preds/logits:0.014047265 log_pplx:4.9854736 log_pplx/logits:4.9854736 loss:4.9854736 loss/logits:4.9854736 num_samples_in_batch:96
INFO:tensorflow:step:   104 fraction_of_correct_next_step_preds:0.010524165 fraction_of_correct_next_step_preds/logits:0.010524165 log_pplx:4.9925981 log_pplx/logits:4.9925981 loss:4.9925981 loss/logits:4.9925981 num_samples_in_batch:48
INFO:tensorflow:step:   105 fraction_of_correct_next_step_preds:0.0068986509 fraction_of_correct_next_step_preds/logits:0.0068986509 log_pplx:5.0027204 log_pplx/logits:5.0027204 loss:5.0027204 loss/logits:5.0027204 num_samples_in_batch:48
INFO:tensorflow:step:   106 fraction_of_correct_next_step_preds:0.010397326 fraction_of_correct_next_step_preds/logits:0.010397326 log_pplx:4.9780407 log_pplx/logits:4.9780407 loss:4.9780407 loss/logits:4.9780407 num_samples_in_batch:48
INFO:tensorflow:Write summary done: step 101
INFO:tensorflow:step:   101, steps/sec: 0.09, examples/sec: 4.59
INFO:tensorflow:Steps/second: 0.089864, Examples/second: 4.595674
INFO:tensorflow:step:   107 fraction_of_correct_next_step_preds:0.010022573 fraction_of_correct_next_step_preds/logits:0.010022573 log_pplx:5.009697 log_pplx/logits:5.009697 loss:5.009697 loss/logits:5.009697 num_samples_in_batch:48
INFO:tensorflow:Steps/second: 0.089948, Examples/second: 4.597317
INFO:tensorflow:Save checkpoint
WARNING:tensorflow:Issue encountered when serializing __batch_norm_update_dict.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'dict' object has no attribute 'name'
WARNING:tensorflow:Issue encountered when serializing __model_split_id_stack.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'list' object has no attribute 'name'
INFO:tensorflow:Save checkpoint done: /tmp/librispeech/log/train/ckpt-00000108
INFO:tensorflow:step:   108 fraction_of_correct_next_step_preds:0.0051525962 fraction_of_correct_next_step_preds/logits:0.0051525962 log_pplx:4.9994984 log_pplx/logits:4.9994984 loss:4.9994984 loss/logits:4.9994984 num_samples_in_batch:48
INFO:tensorflow:Steps/second: 0.090030, Examples/second: 4.598981
INFO:tensorflow:step:   109 fraction_of_correct_next_step_preds:0.011224868 fraction_of_correct_next_step_preds/logits:0.011224868 log_pplx:4.9820132 log_pplx/logits:4.9820132 loss:4.9820132 loss/logits:4.9820132 num_samples_in_batch:48
INFO:tensorflow:Steps/second: 0.090111, Examples/second: 4.600591
INFO:tensorflow:step:   110 fraction_of_correct_next_step_preds:0.0067334538 fraction_of_correct_next_step_preds/logits:0.0067334538 log_pplx:5.0105591 log_pplx/logits:5.0105591 loss:5.0105591 loss/logits:5.0105591 num_samples_in_batch:48
INFO:tensorflow:Steps/second: 0.090191, Examples/second: 4.602178
INFO:tensorflow:step:   111 fraction_of_correct_next_step_preds:0.0084050633 fraction_of_correct_next_step_preds/logits:0.0084050633 log_pplx:4.9993515 log_pplx/logits:4.9993515 loss:4.9993515 loss/logits:4.9993515 num_samples_in_batch:48
INFO:tensorflow:Steps/second: 0.090269, Examples/second: 4.603743
INFO:tensorflow:step:   112 fraction_of_correct_next_step_preds:0.0077442196 fraction_of_correct_next_step_preds/logits:0.0077442196 log_pplx:4.9817152 log_pplx/logits:4.9817152 loss:4.9817152 loss/logits:4.9817152 num_samples_in_batch:48
```

**Comment by drpngx** [comment]
/CC @rprabhavalkar 

We have tuned this for our setup, which is async training with 8 machines with 4 GPUs each, so the settings might be different. You can try lowering the learning rate. You can set this in the `Task()` function, with something like `p.train.learning_rate = 1e-6` maybe?

**Comment by fanlu** [comment]
Could you give me a command to run this job async in single machine or multi machine?

**Comment by drpngx** [comment]
Please take a look at the [docker test script](https://github.com/tensorflow/lingvo/blob/master/docker/run_distributed.py). Also the `tasks/mt` README file explains the basics.

**Comment by drpngx** [comment]
(There is no such thing as async on a single machine. To run on a single machine, use `--run_locally=gpu`.
