### ISSUE TITLE
Problems about distributed training between two servers

### ISSUE THREAD

**Issue by iamxiaoyubei** [tensorflow/lingvo#121]
I have two machines (server0, server1) that can run lingvo distributedly. I want to use one of the machines (server0) as trainer_client, controller. The other machine (server1) acts as worker. So I ran the following command on server0:
```
bazel-bin/lingvo/trainer.par --cluster_spec=worker=server1:8888@controller=server0:8888@trainer_client=server0:24601 \
  --model=image.mnist.LeNet5 \
  --job="trainer_client,controller" --task=0 --mode=sync --logtostderr \
  --logdir=/tmp/mnist/log
```
I also tried --job=controller,trainer_client

I ran the following command on server1:
```
bazel-bin/lingvo/trainer.par --cluster_spec=worker=server1:8888@controller=server0:8888@trainer_client=server0:24601 \
  --model=image.mnist.LeNet5 \
  --job=worker --task=0 --mode=sync --logtostderr \
  --logdir=/tmp/mnist/log
```

But, I got this error:
```
2019-07-10 08:32:54.199474: E tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:442] Internal: Job "trainer_client,controller" was not defined in cluster
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1562, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1558, in main
    RunnerManager(FLAGS.model).Start()
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1550, in Start
    self.MaybeLaunchTensorFlow()
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1167, in MaybeLaunchTensorFlow
    task_index=FLAGS.task)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/server_lib.py", line 147, in __init__
    self._server = c_api.TF_NewServer(self._server_def.SerializeToString())
tensorflow.python.framework.errors_impl.InternalError: Job "trainer_client,controller" was not defined in cluster
```

So can't I use two machines for distributed training? Can't I run the trainer_client and controller tasks on only one of the machines? (I also tried --job=all which still didn't work)

I tried open two container in server0(one for trainer_client, one for controller).

And I found that the worker in server1 can find these two task(trainer_client, controller) in server0:

However, the trainer_client and controller are always waiting for each other.(although I set their ips to localhost, it also doesn't work)

In addition, I also hope that server0 can be used as a worker(trainer_client&&controller&&worker) and server1 still act as a worker. How should I implement it?

**Comment by drpngx** [comment]
Can you try running each job separately?

Does docker/run_distributed.py work for you?

**Comment by iamxiaoyubei** [comment]
Yes, I can try to run each job separately. I can't use run_distributed.py because it always occur errors. 

However, I have found why this problem occurs. This is mainly a problem with communication between the two dockers from one server.

**Comment by drpngx** [comment]
OK, good to know.

Thanks for the report on run_distributed, we should take a look.
