### ISSUE TITLE
Errors while async distributed training

### ISSUE THREAD

**Issue by iamxiaoyubei** [tensorflow/lingvo#125]
When I trained mnist task with async distributed training. It occurs 
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1562, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1558, in main
    RunnerManager(FLAGS.model).Start()
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1551, in Start
    self.StartRunners(self.CreateRunners(FLAGS.job.split(','), FLAGS.logdir))
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1319, in CreateRunners
    trial)
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1273, in _CreateRunner
    return self.Controller(cfg, *common_args)
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 199, in __init__
    self._model = self.params.cls(self.params)
  File "/tmp/tmpp9Xolm/__main__/lingvo/core/base_layer.py", line 118, in wrapper
    func(self, *args, **kwargs)
  File "/tmp/tmpp9Xolm/__main__/lingvo/core/base_model.py", line 1221, in __init__
    self.CreateChild('_task', p.task)
  File "/tmp/tmpp9Xolm/__main__/lingvo/core/base_layer.py", line 602, in CreateChild
    child = p.cls(p)
  File "/tmp/tmpp9Xolm/__main__/lingvo/core/base_layer.py", line 118, in wrapper
    func(self, *args, **kwargs)
  File "/tmp/tmpp9Xolm/__main__/lingvo/tasks/image/classifier.py", line 119, in __init__
    super(ModelV1, self).__init__(params)
  File "/tmp/tmpp9Xolm/__main__/lingvo/core/base_layer.py", line 118, in wrapper
    func(self, *args, **kwargs)
  File "/tmp/tmpp9Xolm/__main__/lingvo/core/base_model.py", line 275, in __init__
    self.CreateChild('lr_schedule', tp.lr_schedule)
  File "/tmp/tmpp9Xolm/__main__/lingvo/core/base_layer.py", line 602, in CreateChild
    child = p.cls(p)
  File "/tmp/tmpp9Xolm/__main__/lingvo/core/base_layer.py", line 118, in wrapper
    func(self, *args, **kwargs)
  File "/tmp/tmpp9Xolm/__main__/lingvo/core/lr_schedule.py", line 385, in __init__
    assert cluster_params.mode == 'sync'
AssertionError
```
in controller job.

Or occurs this error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1562, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1558, in main
    RunnerManager(FLAGS.model).Start()
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1550, in Start
    self.MaybeLaunchTensorFlow()
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1172, in MaybeLaunchTensorFlow
    value = (tf.constant(1.) + tf.constant(1.)).eval()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 731, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 5568, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 948, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1171, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1368, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.AbortedError: Combined status information from 2 operations:

Status code: Aborted [2x]
  RecvTensor expects a different device incarnation: 5619280302612475418 vs. 13848074159545734017. Your worker job ("/job:controller/replica:0/task:0") was probably restarted. Check your worker job for the reason why it was restarted.
  Additional GRPC error information:
  {"created":"@1563179608.084266244","description":"Error received from peer","file":"external/grpc/src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"RecvTensor expects a different device incarnation: 5619280302612475418 vs. 13848074159545734017. Your worker job ("/job:controller/replica:0/task:0") was probably restarted. Check your worker job for the reason why it was restarted.","grpc_status":10}
         [[node add (defined at bazel-bin/lingvo/trainer.par/__main__.py:1172) ]] [1x]
  Session handle is not found: 706b150a6a27c01a. Possibly this worker ("/job:controller/replica:0/task:0") just restarted. [1x]
(0 successful operations.)

Original stack trace for u'add':
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1562, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1558, in main
    RunnerManager(FLAGS.model).Start()
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1550, in Start
    self.MaybeLaunchTensorFlow()
  File "bazel-bin/lingvo/trainer.par/__main__.py", line 1172, in MaybeLaunchTensorFlow
    value = (tf.constant(1.) + tf.constant(1.)).eval()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 884, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 387, in add
    "Add", x=x, y=y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3605, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2001, in __init__
    self._traceback = tf_stack.extract_stack()
```
in trainer and ps job.

**Comment by jonathanasdf** [comment]
The default lr_schedule requires sync

https://github.com/tensorflow/lingvo/blob/5d80a4ed9a05a34528de68d946b55605cfdbd374/lingvo/tasks/image/classifier.py#L112

change it to a different lr_schedule should work

**Comment by iamxiaoyubei** [comment]
Thank you~ It solved!

**Comment by amrzv** [comment]
The same error is raised when running colab [notebook](https://colab.research.google.com/github/tensorflow/lingvo/blob/master/codelabs/introduction.ipynb).
