### ISSUE TITLE
Punctuator fails on GPU (No registered 'AssertSameDim0' OpKernel for GPU devices compatible with node ...)

### ISSUE THREAD

**Issue by kristofgiber** [tensorflow/lingvo#126]
My training fails with '_Failed to create kernel_' and '_...no registered GPU devices compatible with node..._' errors (see the logs below) when I execute `bazel-bin/lingvo/trainer --logtostderr --model=punctuator.codelab.RNMTModel --mode=sync --logdir=/tmp/punctuator --saver_max_to_keep=2 --run_locally=gpu` from the Punctuator example.

I have the latest lingvo and tf-nightly-gpu (1.15.0.dev20190715) installed, my NVIDIA-CUDA settings look fine, `tf.test.is_gpu_available(cuda_only=False, min_cuda_compute_capability=None)` returns True and the GPU works fine on other examples, such as the MNIST example with GPU (bazel-bin/lingvo/trainer --logtostderr --run_locally=gpu --model=image.mnist.LeNet5 --logdir=/tmp/mnist/log --mode=sync).

I have found a tf bug reported that may be related: https://github.com/tensorflow/hub/issues/160
but I have the suggested fix in place already (use tf-nightly-gpu later than 1.14.1) and I am not sure it is the same problem.

I did not have this problem when running punctuator with a previous version of lingvo.

Logs:

...
I0716 23:16:58.960727 140435381413632 trainer.py:503] Probably the expected race on global_step: From /job:local/replica:0/task:0:
Attempting to use uninitialized value global_step
	 [[{{node _send_global_step_0}}]]
I0716 23:17:01.899094 140435389806336 trainer.py:363] Initialize variables done.
I0716 23:17:03.796235 140435389806336 trainer.py:419] Steps/second: 0.000000, Examples/second: 0.000000
I0716 23:17:03.796720 140435389806336 trainer.py:337] Save checkpoint
I0716 23:17:07.340193 140435381413632 retry.py:71] Retry: caught exception: _WaitTillInit while running FailedPreconditionError: From /job:local/replica:0/task:0:
Attempting to use uninitialized value global_step
	 [[{{node _send_global_step_0}}]]
. Call failed at (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/kristofgiber/lingvo/lingvo/trainer.py", line 468, in Start
    self._RunLoop('trainer', self._Loop)
  File "/home/kristofgiber/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/retry.py", line 53, in Wrapper
    return func(*args, **kwargs)
  File "/home/kristofgiber/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/base_runner.py", line 190, in _RunLoop
    loop_func(*loop_args)
Traceback for above exception (most recent call last):
  File "/home/kristofgiber/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/retry.py", line 53, in Wrapper
    return func(*args, **kwargs)
  File "/home/kristofgiber/lingvo/lingvo/trainer.py", line 501, in _WaitTillInit
    global_step = sess.run(py_utils.GetGlobalStep())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 941, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 1164, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 1342, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    raise type(e)(node_def, op, message)
Waiting for 12.76 seconds before retrying.
I0716 23:17:07.341211 140435381413632 base_runner.py:107] step:     0
2019-07-16 23:17:33.579180: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2019-07-16 23:17:35.259462: I ./lingvo/core/ops/input_common.h:71] Create RecordProcessor
2019-07-16 23:17:35.518934: I lingvo/core/ops/input_common.cc:33] Input source weights are empty, fall back to legacy behavior.
2019-07-16 23:17:35.519087: I lingvo/core/ops/record_yielder.cc:292] 0x7fb7e6631530 Record yielder start
2019-07-16 23:17:35.519108: I lingvo/core/ops/record_yielder.cc:294] Randomly seed RecordYielder.
2019-07-16 23:17:35.519138: I ./lingvo/core/ops/input_common.h:76] Create batcher
2019-07-16 23:17:35.519193: I lingvo/core/ops/record_yielder.cc:351] Epoch 1 /tmp/punctuator_data/train.txt
2019-07-16 23:17:39.655677: E tensorflow/core/common_runtime/executor.cc:642] Executor failed to create kernel. Not found: No registered 'AssertSameDim0' OpKernel for GPU devices compatible with node {{node AssertSameDim0}}
	.  Registered:  device='CPU'

	 [[AssertSameDim0]]
2019-07-16 23:17:39.849115: I lingvo/core/ops/record_yielder.cc:321] 0x7fb7e6631530Basic record yielder exit
I0716 23:17:40.182132 140435381413632 base_runner.py:230] trainer done (fatal error).
I0716 23:17:40.182456 140435381413632 base_runner.py:107] trainer exception: From /job:local/replica:0/task:0:
No registered 'AssertSameDim0' OpKernel for GPU devices compatible with node {{node AssertSameDim0}}
	.  Registered:  device='CPU'

	 [[AssertSameDim0]]
	 [[fprop/punctuator_rnmt/tower_0_0/enc/L0/Forward_z4J4BjskUyE_1]]

E0716 23:17:40.183589 140435381413632 base_runner.py:237] Traceback (most recent call last):
E0716 23:17:40.183743 140435381413632 base_runner.py:237]   File "/home/kristofgiber/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/base_runner.py", line 190, in _RunLoop
E0716 23:17:40.183828 140435381413632 base_runner.py:237]     loop_func(*loop_args)
E0716 23:17:40.183900 140435381413632 base_runner.py:237]   File "/home/kristofgiber/lingvo/lingvo/trainer.py", line 556, in _Loop
E0716 23:17:40.183980 140435381413632 base_runner.py:237]     model_task.per_example_tensors,
E0716 23:17:40.184067 140435381413632 base_runner.py:237]   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 941, in run
E0716 23:17:40.184123 140435381413632 base_runner.py:237]     run_metadata_ptr)
E0716 23:17:40.184175 140435381413632 base_runner.py:237]   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 1164, in _run
E0716 23:17:40.184227 140435381413632 base_runner.py:237]     feed_dict_tensor, options, run_metadata)
E0716 23:17:40.184279 140435381413632 base_runner.py:237]   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 1342, in _do_run
E0716 23:17:40.184330 140435381413632 base_runner.py:237]     run_metadata)
E0716 23:17:40.184381 140435381413632 base_runner.py:237]   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
E0716 23:17:40.184475 140435381413632 base_runner.py:237]     raise type(e)(node_def, op, message)
E0716 23:17:40.184571 140435381413632 base_runner.py:237] NotFoundError: From /job:local/replica:0/task:0:
E0716 23:17:40.184633 140435381413632 base_runner.py:237] No registered 'AssertSameDim0' OpKernel for GPU devices compatible with node {{node AssertSameDim0}}
E0716 23:17:40.184689 140435381413632 base_runner.py:237] 	.  Registered:  device='CPU'
E0716 23:17:40.184755 140435381413632 base_runner.py:237] 
E0716 23:17:40.184806 140435381413632 base_runner.py:237] 	 [[AssertSameDim0]]
E0716 23:17:40.184855 140435381413632 base_runner.py:237] 	 [[fprop/punctuator_rnmt/tower_0_0/enc/L0/Forward_z4J4BjskUyE_1]]
E0716 23:17:40.184947 140435381413632 base_runner.py:237] 

Process finished with exit code 1

**Comment by jonathanasdf** [comment]
Hm, I tried your command as-is with tf-nightly-gpu 1.15.0.dev20190715 and the latest lingvo and it ran fine for me.

Did you make sure to build trainer with --config=cuda? That should enable the DEFINE for the gpu kernel: https://github.com/tensorflow/lingvo/blob/fd53eaffacf17625b0f9fb0d9f1ffedc28c9244d/lingvo/core/ops/assert_kernels.cc#L107

**Comment by kristofgiber** [comment]
That was it! `bazel build -c opt //lingvo:trainer --config=cuda`
It's running fine now, thank you!
