### ISSUE TITLE
model inference (calling model registry) fails with unparsed flag access error

### ISSUE THREAD

**Issue by kristofgiber** [tensorflow/lingvo#131]
I figured it is better to open a separate issue for this problem. We are using the Model Inference code in [Lingvo introduction](https://colab.research.google.com/github/tensorflow/lingvo/blob/master/codelabs/introduction.ipynb) without any modification (not on Colab though but in a Pycharm based framework). 

The model was trained without problem and the checkpoint is available yet model inference fails with the following error: 

`"absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --model_params_override before flags were parsed."`

The error is apparently triggered by model_registry simply checking for the already defined flags which for some reason make `python2.7/dist-packages/absl` flag checking to fail with unparsed flag error (this flag checking is used by lingvo in place of tensorflow's flags).

Here are the logs:

Using checkpoint /tmp/punctuator/train/ckpt-00001448
E0723 12:50:26.152736 140272753321728 _flagvalues.py:490] Trying to access flag --model_params_override before flags were parsed.
Traceback (most recent call last):
File "/home/kristofgiber/pycharm_uploads/gcloud/gcloud_vm_gpu/lingvo_punctuator_inference.py", line 38, in 
params = model_registry.GetParams('punctuator.codelab.RNMTModel', 'Test')
File "/home/kristofgiber/lingvo/bazel-out/k8-py3-opt/bin/lingvo/ipython_kernel.runfiles/main/lingvo/model_registry.py", line 223, in GetParams
_MaybeUpdateParamsFromFlags(cfg)
File "/home/kristofgiber/lingvo/bazel-out/k8-py3-opt/bin/lingvo/ipython_kernel.runfiles/main/lingvo/model_registry.py", line 52, in _MaybeUpdateParamsFromFlags
if FLAGS.model_params_override and FLAGS.model_params_file_override:
File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 491, in getattr
raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --model_params_override before flags were parsed.

**Comment by jonathanasdf** [comment]
I think we assumed that the previous cells would be run already. I think it's the tf.app.run() call that sets up the flags. Maybe adding something like this to the top would work

`tf.app.run(lambda _: None)`

**Comment by kristofgiber** [comment]
I tried this (and also tried with import tensorflow as tf changed to import lingvo.compat as tf) but I get the following error (and system exit) when calling the tf.app.run(lambda _: None) line right after the tf import:

tf.app.run(lambda _: None)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-44f377f77832>", line 1, in <module>
    tf.app.run(lambda _: None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
SystemExit

**Comment by jonathanasdf** [comment]
Hm, can you try this:

```
imports
def main(unused_argv):
  checkpoint = ...
  ...
tf.app.run(main)
```

If it still errors with SystemExit maybe even wrap the tf.app.run in try/except.

**Comment by kristofgiber** [comment]
Both way works (def main and try/except), thank you!

**Comment by kristofgiber** [comment]
Thank you for the fix and just to clarify my last comment, it works either way. No need to add both. Sorry for the confusion
