### ISSUE TITLE
bazel test error on bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.cc

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/lingvo#137]
```
(/home/luban/env/tfnightly-py3.6) [luban@k8s-deploy-ikt4jd-1563350504836-84d4487cd6-vxt92 lingvo]$ bazel test -c opt --sandbox_debug //lingvo:trainer_test //lingvo:models_test
INFO: Analysed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 test targets...
ERROR: /home/luban/lingvo/lingvo/core/ops/BUILD:377:1: C++ compilation of rule '//lingvo/core/ops:hyps_proto' failed (Exit 1) process-wrapper failed: error executing command 
  (cd /home/luban/.cache/bazel/_bazel_luban/58779add9ad7f0a0d87616949a625edd/sandbox/processwrapper-sandbox/4/execroot/__main__ && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64: \
    PATH=/usr/local/git/bin:/home/luban/env/tfnightly-py3.6/bin:/home/luban/anaconda3/bin:/home/luban/anaconda3/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/luban/.local/bin:/home/luban/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /home/luban/.cache/bazel/_bazel_luban/install/7da6a92c096ada842b8d48c251312343/_embedded_binaries/process-wrapper '--timeout=0' '--kill_delay=15' /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/lingvo/core/ops/_objs/hyps_proto/hyps.pb.pic.d '-frandom-seed=bazel-out/k8-opt/bin/lingvo/core/ops/_objs/hyps_proto/hyps.pb.pic.o' -fPIC -iquote . -iquote bazel-out/k8-opt/genfiles -iquote bazel-out/k8-opt/bin -iquote external/tensorflow_includes -iquote bazel-out/k8-opt/genfiles/external/tensorflow_includes -iquote bazel-out/k8-opt/bin/external/tensorflow_includes -iquote external/absl_includes -iquote bazel-out/k8-opt/genfiles/external/absl_includes -iquote bazel-out/k8-opt/bin/external/absl_includes -iquote external/eigen_archive -iquote bazel-out/k8-opt/genfiles/external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/protobuf_archive -iquote bazel-out/k8-opt/genfiles/external/protobuf_archive -iquote bazel-out/k8-opt/bin/external/protobuf_archive -isystem external/tensorflow_includes/tensorflow_includes -isystem bazel-out/k8-opt/genfiles/external/tensorflow_includes/tensorflow_includes -isystem bazel-out/k8-opt/bin/external/tensorflow_includes/tensorflow_includes -isystem external/absl_includes/absl -isystem bazel-out/k8-opt/genfiles/external/absl_includes/absl -isystem bazel-out/k8-opt/bin/external/absl_includes/absl -isystem external/eigen_archive/tf_includes -isystem bazel-out/k8-opt/genfiles/external/eigen_archive/tf_includes -isystem bazel-out/k8-opt/bin/external/eigen_archive/tf_includes -isystem external/protobuf_archive/tf_includes -isystem bazel-out/k8-opt/genfiles/external/protobuf_archive/tf_includes -isystem bazel-out/k8-opt/bin/external/protobuf_archive/tf_includes '-D_GLIBCXX_USE_CXX11_ABI=0' -Wno-sign-compare -mavx -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.cc -o bazel-out/k8-opt/bin/lingvo/core/ops/_objs/hyps_proto/hyps.pb.pic.o)
In file included from bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.cc:4:0:
bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers. Please update
  ^
bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.cc:4:0:
bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.h:38:1: error: 'PROTOBUF_NAMESPACE_OPEN' does not name a type
 PROTOBUF_NAMESPACE_OPEN
 ^
bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.h:42:1: error: 'PROTOBUF_NAMESPACE_CLOSE' does not name a type
 PROTOBUF_NAMESPACE_CLOSE
 ^
bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.h:67:1: error: 'PROTOBUF_NAMESPACE_OPEN' does not name a type
 PROTOBUF_NAMESPACE_OPEN
 ^
bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.h:69:55: error: 'Arena' has not been declared
 template<> ::tensorflow::lingvo::Hypothesis_AttenVec* Arena::CreateMaybeMessage<::tensorflow::lingvo::Hypothesis_AttenVec>(Arena*);
                                                       ^
bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.h:69:80: error: expected initializer before '<' token
 template<> ::tensorflow::lingvo::Hypothesis_AttenVec* Arena::CreateMaybeMessage<::tensorflow::lingvo::Hypothesis_AttenVec>(Arena*);
                                                                                ^
In file included from bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.cc:4:0:
bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.h:70:1: error: 'PROTOBUF_NAMESPACE_CLOSE' does not name a type
 PROTOBUF_NAMESPACE_CLOSE
 ^
bazel-out/k8-opt/genfiles/lingvo/core/ops/hyps.pb.h:404:30: error: expected declaration before end of line
   #pragma GCC diagnostic push
                              ^
INFO: Elapsed time: 4.405s, Critical Path: 4.15s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
//lingvo:models_test                                                  NO STATUS

FAILED: Build did NOT complete successfully
```

```
(/home/luban/env/tfnightly-py3.6) [luban@k8s-deploy-ikt4jd-1563350504836-84d4487cd6-vxt92 lingvo]$ cat tf_env.txt 

== cat /etc/issue ===============================================
Linux k8s-deploy-ikt4jd-1563350504836-84d4487cd6-vxt92 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="7 (Core)"
VERSION_ID="7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

== are we in docker =============================================
No

== compiler =====================================================
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== bazel =====================================================
Build label: 0.24.1
Build time: Tue Apr 2 16:29:26 2019 (1554222566)
Build timestamp: 1554222566
Build timestamp as int: 1554222566

== uname -a =====================================================
Linux k8s-deploy-ikt4jd-1563350504836-84d4487cd6-vxt92 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                         1.16.4              
protobuf                      3.9.0               
tensorflow-estimator          1.14.0              
tensorflow-gpu                1.14.0              

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.14.0
tf.GIT_VERSION = v1.14.0-rc1-22-gaf24dc91b5
tf.COMPILER_VERSION = v1.14.0-rc1-22-gaf24dc91b5
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Tue Aug  6 16:23:01 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           On   | 00000000:84:00.0 Off |                    0 |
| N/A   29C    P0    55W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0.130
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart_static.a
```

**Comment by zh794390558** [comment]
uninstall 
```
tensorflow-estimator          1.14.0              
tensorflow-gpu                1.14.0  
protobuf                      3.9.0    
```

install protobuf  3.8.0

**Comment by zh794390558** [comment]
```

== cat /etc/issue ===============================================
Linux k8s-deploy-ikt4jd-1563350504836-84d4487cd6-vxt92 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="7 (Core)"
VERSION_ID="7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

== are we in docker =============================================
No

== compiler =====================================================
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== bazel =====================================================
Build label: 0.24.1
Build time: Tue Apr 2 16:29:26 2019 (1554222566)
Build timestamp: 1554222566
Build timestamp as int: 1554222566

== uname -a =====================================================
Linux k8s-deploy-ikt4jd-1563350504836-84d4487cd6-vxt92 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                         1.16.4              
protobuf                      3.8.0               

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.15.0-dev20190730
tf.GIT_VERSION = v1.12.1-7396-g12481e7e74
tf.COMPILER_VERSION = v1.12.1-7396-g12481e7e74
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Tue Aug  6 16:49:39 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           On   | 00000000:84:00.0 Off |                    0 |
| N/A   29C    P0    55W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0.130
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart_static.a
```

**Comment by zh794390558** [comment]
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //lingvo:trainer_test
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/luban/.cache/bazel/_bazel_luban/58779add9ad7f0a0d87616949a625edd/sandbox/processwrapper-sandbox/23/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer_test.runfiles/__main__/lingvo/trainer_test.py", line 28, in <module>
    from lingvo import model_registry
  File "/home/luban/.cache/bazel/_bazel_luban/58779add9ad7f0a0d87616949a625edd/sandbox/processwrapper-sandbox/23/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer_test.runfiles/__main__/lingvo/model_registry.py", line 28, in <module>
    from lingvo.core import base_model_params
  File "/home/luban/.cache/bazel/_bazel_luban/58779add9ad7f0a0d87616949a625edd/sandbox/processwrapper-sandbox/23/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer_test.runfiles/__main__/lingvo/core/base_model_params.py", line 21, in <module>
    from lingvo.core import base_input_generator
  File "/home/luban/.cache/bazel/_bazel_luban/58779add9ad7f0a0d87616949a625edd/sandbox/processwrapper-sandbox/23/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer_test.runfiles/__main__/lingvo/core/base_input_generator.py", line 23, in <module>
    from lingvo.core import base_layer
  File "/home/luban/.cache/bazel/_bazel_luban/58779add9ad7f0a0d87616949a625edd/sandbox/processwrapper-sandbox/23/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer_test.runfiles/__main__/lingvo/core/base_layer.py", line 24, in <module>
    from lingvo.core import cluster_factory
  File "/home/luban/.cache/bazel/_bazel_luban/58779add9ad7f0a0d87616949a625edd/sandbox/processwrapper-sandbox/23/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer_test.runfiles/__main__/lingvo/core/cluster_factory.py", line 21, in <module>
    from lingvo.core import cluster
  File "/home/luban/.cache/bazel/_bazel_luban/58779add9ad7f0a0d87616949a625edd/sandbox/processwrapper-sandbox/23/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer_test.runfiles/__main__/lingvo/core/cluster.py", line 26, in <module>
    from lingvo.core import py_utils
  File "/home/luban/.cache/bazel/_bazel_luban/58779add9ad7f0a0d87616949a625edd/sandbox/processwrapper-sandbox/23/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer_test.runfiles/__main__/lingvo/core/py_utils.py", line 44, in <module>
    from tensorflow.contrib.model_pruning.python.layers import core_layers as pruning_layers
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/site-packages/tensorflow_core/contrib/__init__.py", line 39, in <module>
    from tensorflow.contrib import compiler
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/site-packages/tensorflow_core/contrib/compiler/__init__.py", line 21, in <module>
    from tensorflow.contrib.compiler import jit
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/site-packages/tensorflow_core/contrib/compiler/__init__.py", line 22, in <module>
    from tensorflow.contrib.compiler import xla
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/site-packages/tensorflow_core/contrib/compiler/xla.py", line 22, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/site-packages/tensorflow_core/python/estimator/model_fn.py", line 26, in <module>
    from tensorflow_estimator.python.estimator import model_fn
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/home/luban/env/tfnightly-py3.6/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 23, in <module>
    from tensorflow.python.feature_column import dense_features
ImportError: cannot import name 'dense_features'
```

**Comment by zh794390558** [comment]
```
(/home/luban/env/tfnightly-py3.6) [luban@k8s-deploy-ikt4jd-1563350504836-84d4487cd6-vxt92 lingvo]$ vi /home/luban/.cache/bazel/_bazel_luban/58779add9ad7f0a0d87616949a625edd/execroot/__main__/bazel-out/k8-opt/testlogs/lingvo/trainer_test/shard_4_of_5/test.log
(/home/luban/env/tfnightly-py3.6) [luban@k8s-deploy-ikt4jd-1563350504836-84d4487cd6-vxt92 lingvo]$ bazel test -j 1 -c opt //lingvo:trainer_test //lingvo:models_test                                                                                  INFO: Analysed 2 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 test targets...
[14 / 15] 1 / 2 tests;  1 action; last test: //lingvo:models_test
    Testing //lingvo:trainer_test (shard 3 of 5); 25s processwrapper-sandbox


[14 / 15] 1 / 2 tests;  1 action; last test: //lingvo:models_test
    Testing //lingvo:trainer_test (shard 3 of 5); 26s processwrapper-sandbox
INFO: Elapsed time: 221.769s, Critical Path: 94.49s
INFO: 3 processes: 3 processwrapper-sandbox.
INFO: Build completed successfully, 4 total actions
//lingvo:models_test                                            (cached) PASSED in 20.0s
//lingvo:trainer_test                                       (2/5 cached) PASSED in 98.9s
  Stats over 5 runs: max = 98.9s, min = 11.2s, avg = 66.3s, dev = 34.0s

Executed 1 out of 2 tests: 2 tests pass.
INFO: Build completed successfully, 4 total actions
```


```

== cat /etc/issue ===============================================
Linux k8s-deploy-ikt4jd-1563350504836-84d4487cd6-vxt92 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
VERSION="7 (Core)"
VERSION_ID="7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

== are we in docker =============================================
No

== compiler =====================================================
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


== bazel =====================================================
Build label: 0.24.1
Build time: Tue Apr 2 16:29:26 2019 (1554222566)
Build timestamp: 1554222566
Build timestamp as int: 1554222566

== uname -a =====================================================
Linux k8s-deploy-ikt4jd-1563350504836-84d4487cd6-vxt92 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy                         1.16.4              
protobuf                      3.8.0               

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.15.0-dev20190730
tf.GIT_VERSION = v1.12.1-7396-g12481e7e74
tf.COMPILER_VERSION = v1.12.1-7396-g12481e7e74
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Tue Aug  6 17:14:40 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P40           On   | 00000000:84:00.0 Off |                    0 |
| N/A   34C    P0    56W / 250W |      0MiB / 22919MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0.130
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart_static.a
```

pip list
```
tf-estimator-nightly          1.14.0.dev2019073001
tf-nightly-gpu                1.15.0.dev20190730  
```
