### ISSUE TITLE
 About preprocessing data in ASR

### ISSUE THREAD

**Issue by alessiaatunimi** [tensorflow/lingvo#146]
Hi,
I'm trying to download preprocess the dataset for the ASR task with the files: _lingvo/tasks/asr/tools/librispeech.03.parameterize_train.sh_ and _lingvo/tasks/asr/tools/librispeech.04.parameterize_devtest.sh_. 
I want to put them in a volume folder, so that I don't lose data when the container stops.

Here's what I did:

**Setting up environment**

$ LINGVO_DIR="/tmp/lingvo”
$ rm -rf "$LINGVO_DIR"
$ git clone https://github.com/tensorflow/lingvo.git "$LINGVO_DIR"
$ cd "$LINGVO_DIR"

**Create docker image**

$ docker build --tag tensorflow:lingvo - < docker/dev.dockerfile --no-cache

**Create docker volume for the dataset**
$ docker volume create librispeech

**Run container with the empty volume for the dataset and the volume with the repository folder**
$ docker run -it -v librispeech:/tmp/librispeech -v ${LINGVO_DIR}:/tmp/lingvo --name lingvo tensorflow:lingvo bash

**this pass, so I'm good**
$ bazel test -c opt //lingvo/core/ops:beam_search_step_op_test

**Download dataset**

$ lingvo/tasks/asr/tools/librispeech.01.download_train.sh
$ lingvo/tasks/asr/tools/librispeech.02.download_devtest.sh

**Parametrize dataset**
	
$ bazel build -c opt //lingvo/tools:create_asr_features

**Here's when I get the error:** 

$ lingvo/tasks/asr/tools/librispeech.03.parameterize_train.sh

**error**:

`I0819 21:27:02.294093 140003015599872 create_asr_features.py:84] First pass: loading text files...
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 213, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 204, in main
    _DumpTranscripts()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 117, in _DumpTranscripts
    trans = _ReadTranscriptions()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 108, in _ReadTranscriptions
    uttid, txt = l.strip('\n').split(' ', 1)
TypeError: a bytes-like object is required, not 'str'`

Can someone tell me why?
Thanks

**Comment by drpngx** [comment]
Are you running on py3 by any chance?

**Comment by alessiaatunimi** [comment]
If you mean the python version I'm using Python 2.7.12. It's not the first time that I run this file and it always worked...

**Comment by drpngx** [comment]
Nothing springs to mind. Can you print `type(l)`?

**Comment by alessiaatunimi** [comment]
The only thing that I changed from the other time that this file run correctly is that I made /tmp/librispeech a volume... could it be a problem?

**Comment by drpngx** [comment]
I don't really understand why `readlines` would return bytes instead of a
string. Just do `str(l).strip(..).split(..)` instead. You can send a pull
request.

**Comment by alessiaatunimi** [comment]
I changed the line:

`uttid, txt = l.strip('\n').split(' ', 1)`

into

`uttid, txt = str(l).strip('\n').split(' ', 1)`

In this way the First pass ("=== First pass, collecting transcripts: ${subset}") went well for every subset. Then, for each subset, the second pass(  "=== Second pass, parameterization: ${subset}") ends in this way:

```
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 213, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 206, in main
    _CreateAsrFeatures()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 190, in _CreateAsrFeatures
    assert uttid in trans, uttid
AssertionError: 374-180298-0038
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 213, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 206, in main
    _CreateAsrFeatures()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 190, in _CreateAsrFeatures
    assert uttid in trans, uttid
AssertionError: 374-180298-0060
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 213, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 206, in main
    _CreateAsrFeatures()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 190, in _CreateAsrFeatures
    assert uttid in trans, uttid
AssertionError: 374-180298-0006
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 213, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 206, in main
    _CreateAsrFeatures()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 190, in _CreateAsrFeatures
    assert uttid in trans, uttid
AssertionError: 374-180298-0021
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 213, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 206, in main
    _CreateAsrFeatures()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 190, in _CreateAsrFeatures
    assert uttid in trans, uttid
AssertionError: 374-180298-0028
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 213, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 206, in main
    _CreateAsrFeatures()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 190, in _CreateAsrFeatures
    assert uttid in trans, uttid
AssertionError: 374-180298-0022
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 213, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 206, in main
    _CreateAsrFeatures()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 190, in _CreateAsrFeatures
    assert uttid in trans, uttid
AssertionError: 374-180298-0044
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 213, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 206, in main
    _CreateAsrFeatures()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 190, in _CreateAsrFeatures
    assert uttid in trans, uttid
AssertionError: 374-180298-0036
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 213, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 206, in main
    _CreateAsrFeatures()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 190, in _CreateAsrFeatures
    assert uttid in trans, uttid
AssertionError: 374-180298-0045
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 213, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 206, in main
    _CreateAsrFeatures()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/tools/create_asr_features.runfiles/__main__/lingvo/tools/create_asr_features.py", line 190, in _CreateAsrFeatures
    assert uttid in trans, uttid
AssertionError: 374-180298-0051
+ touch FAILED
+ touch FAILED
+ touch FAILED
+ touch FAILED
+ touch FAILED
+ touch FAILED
+ touch FAILED
+ touch FAILED
+ touch FAILED
+ touch FAILED

```

**Comment by alessiaatunimi** [comment]
An other weird thing:

after running the two preprocessing files, in my volumes I get:

- **train** folder:
<img width="1114" alt="Screen Shot 2019-08-20 at 4 04 37 PM" src="https://user-images.githubusercontent.com/53495648/63384342-3f709700-c364-11e9-99a1-17898adb5e87.png">


- **devtest** folder:
dev-clean.tfrecords-00000-of-00001

Then when I run the trainer in this way:
```
$ bazel clean
$ bazel build -c opt lingvo:trainer   (note: no --config=cuda)
$ CUDA_VISIBLE_DEVICES= bazel-bin/lingvo/trainer --run_locally=cpu --mode=sync --model=asr.librispeech.Librispeech960Base --logdir=/tmp/asr/log --logtostderr 
```
it doesn't work, saying that 
`bash: bazel-bin/lingvo/trainer: No such file or directory`

but if I run:

`bazel run -c opt //lingvo:trainer -- --logtostderr --model=asr.librispeech.Librispeech960Grapheme --mode=sync --logdir=/tmp/asr/log --run_locally=cpu`

seems to work, but then after the first checkpoint:

```
I0820 20:43:43.302897 139667613669120 checkpointer.py:100] Save checkpoint done: /tmp/asr/log/train/ckpt-00000000

2019-08-20 20:43:47.383517: I ./lingvo/core/ops/input_common.h:71] Create RecordProcessor

2019-08-20 20:43:47.384291: I lingvo/core/ops/input_common.cc:33] Input source weights are empty, fall back to legacy behavior.

2019-08-20 20:43:47.384933: I lingvo/core/ops/record_yielder.cc:324] 0x7f06d2c92f00 Record yielder start

2019-08-20 20:43:47.384969: I lingvo/core/ops/record_yielder.cc:326] Randomly seed RecordYielder.

2019-08-20 20:43:47.384991: I ./lingvo/core/ops/input_common.h:76] Create batcher
```

it just continue to print those lines:

```
2019-08-20 20:43:47.385009: I lingvo/core/ops/record_yielder.cc:383] Epoch 1 /tmp/librispeech/train/train.tfrecords-*

2019-08-20 20:43:47.393038: I lingvo/core/ops/record_yielder.cc:430] Epoch 1: total records 0

2019-08-20 20:43:47.393133: I lingvo/core/ops/record_yielder.cc:383] Epoch 1 /tmp/librispeech/train/train.tfrecords-*

2019-08-20 20:43:47.399674: I lingvo/core/ops/record_yielder.cc:430] Epoch 1: total records 0

2019-08-20 20:43:47.399777: I lingvo/core/ops/record_yielder.cc:383] Epoch 1 /tmp/librispeech/train/train.tfrecords-*
```

Do you know why?

**Comment by alessiaatunimi** [comment]
### SOLUTION

Finally understand from where did that problem came from.
Seeing that I changed the line:

`uttid, txt = l.strip('\n').split(' ', 1)`

into

`uttid, txt = str(l).strip('\n').split(' ', 1)`

uttid was stringified, and so the line

`trans[uttid] = text`  created a dictionary like:

`"b'6877-77361-0040": "IT ENTERED INTO MY THOUGHTS THAT I MIGHT END THE MATTER NOW AND LET THESE OTHERS GO TO WADE OUT INTO THE SEA INTO THIS WARM LAPPING THAT MINGLED THE NATURES OF WATER AND LIGHT TO STAND THERE BREAST HIGH\\n'"`

and so trans[uttid] didn't work.
I solved changing a little bit the _ReadTranscription() function:

```
def _ReadTranscriptions():
  """Read all transcription files from the tarball.
  Returns:
    A map of utterance id to upper case transcription.
  """
  tar = tarfile.open(FLAGS.input_tarball, mode='r:gz')
  n = 0
  tf.logging.info('First pass: loading text files...')
  trans = {}
  for tarinfo in tar:
    if not tarinfo.isreg():
      continue
    n += 1
    if 0 == n % 10000:
      tf.logging.info('Scanned %d entries...', n)
    if not tarinfo.name.endswith('.trans.txt'):
      continue
    key = tarinfo.name.strip('.trans.txt')
    f = tar.extractfile(tarinfo)
    u = 0
    #beginning of part changed
    for l in f.readlines():
      uttid, txt = str(l).strip('\n').split(' ', 1)
      #add if-else condition because some uttid was in the form "b'_numbers_" and others 'b"numbers' and so one split wasn't enough 
      if len(uttid.split("b'"))>1:
        trans[uttid.split("b'")[1]] = txt
      else:
        trans[uttid.split('b"')[1]] = txt
      #end of part changed
      u += 1
    tf.logging.info('[%s] = %d utterances', key, u)
    f.close()
  return trans
```

In this was seems to work

**Comment by manish-kumar-garg** [comment]
@alessiaatunimi  I faced the same issue. It is fixed by using the solution you suggested.
Thanks
