### ISSUE TITLE
(tensorflow_cpu) C:\tensorflow1\models\research\object_detection>python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_pets.config --trained_checkpoint_prefix training/model.ckpt-XXXX --output_directory inference_graph >temp 2019-10-23 19:31:29.262010: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found 2019-10-23 19:31:29.278061: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine. WARNING:tensorflow: The TensorFlow contrib module will not be included in TensorFlow 2.0. For more information, please see:   * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md   * https://github.com/tensorflow/addons   * https://github.com/tensorflow/io (for I/O related ops) If you depend on functionality not listed there, please file an issue.

### ISSUE THREAD

**Issue by rakeshkp2003** [tensorflow/lingvo#165]
(tensorflow_cpu) C:\tensorflow1\models\research\object_detection>python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_inception_v2_pets.config --trained_checkpoint_prefix training/model.ckpt-XXXX --output_directory inference_graph >temp
2019-10-23 19:31:29.262010: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2019-10-23 19:31:29.278061: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "export_inference_graph.py", line 162, in <module>
    tf.app.run()
  File "C:\Users\rakes\Anaconda2\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\rakes\Anaconda2\envs\tensorflow_cpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\rakes\Anaconda2\envs\tensorflow_cpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "export_inference_graph.py", line 158, in main
    write_inference_graph=FLAGS.write_inference_graph)
  File "C:\tensorflow1\models\research\object_detection\exporter.py", line 489, in export_inference_graph
    write_inference_graph=write_inference_graph)
  File "C:\tensorflow1\models\research\object_detection\exporter.py", line 418, in _export_inference_graph
    trained_checkpoint_prefix=checkpoint_to_use)
  File "C:\tensorflow1\models\research\object_detection\exporter.py", line 327, in write_graph_and_checkpoint
    saver.restore(sess, trained_checkpoint_prefix)
  File "C:\Users\rakes\Anaconda2\envs\tensorflow_cpu\lib\site-packages\tensorflow_core\python\training\saver.py", line 1282, in restore
    checkpoint_prefix)
ValueError: The passed save_path is not a valid checkpoint: training/model.ckpt-XXXX

Not sure why this issue is coming. Can someone help

**Comment by jonathanasdf** [comment]
I think you are posting in the wrong place. Probably you want https://github.com/tensorflow/models/tree/master/research/object_detection
