### ISSUE TITLE
AssertionError: assert filtered_vmap is not None in ComputeGradients

### ISSUE THREAD

**Issue by manish-kumar-garg** [tensorflow/lingvo#168]
I have written a custom model for asr task and defined ComputePredictions and ComputeLoss. I am getting some error while calculating gradients.

ComputePredictions

`

def ComputePredictions(self, theta, input_batch):

    p=self.params
    input_batch_src = input_batch.src
    input_batch_tgt = input_batch.tgt
    paddings = input_batch_tgt.paddings
    encoder_outputs = self._FrontendAndEncoderFProp(theta, input_batch_src)
    encoder_outputs = encoder_outputs.encoded
    ids = input_batch_tgt.ids
    batch_size = tf.shape(ids)[1]
    state0 = self.lm.zero_state(theta.lm, batch_size)
    lm_out, _ = self.lm.FProp(theta.lm, ids, paddings, state0)
    activation = lm_out.last_hidden  # [time, batch, dim]
    lm_logits = lm_out.logits
    out = tf.concat([encoder_outputs, activation], axis=2)
    out = self.fc1.FProp(theta.fc1, out)
    out = self.fc2.FProp(theta.fc2, out)
    return py_utils.NestedMap(act=out, logits=out)
`

ComputeLoss:

`
def ComputeLoss(self, theta, predictions, input_batch):

    logits = predictions.logits
    tgt = input_batch.tgt
    tgt.logits = tf.dtypes.cast(tgt.ids, tf.float32)
    loss = py_utils.SigmoidCrossEntropyFocalLoss(logits, tgt.logits)
    metrics = {
            'loss': (10.0, 20.0),
            'log_pplx': (30.0, 40.0),
            'token_normed_prob': (50.0, 60.0),
            'fraction_of_correct_next_step_preds': (0.9, 0.8)
            }
    return metrics, {'loss': tf.reduce_sum(loss)}

`
Error:

`I1107 11:02:10.024179 140506572162816 learner.py:167] loss: bprop variable: librispeech/lm/softmax/weight_0/var:0
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1837, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1832, in main
    RunnerManager(FLAGS.model).Start()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1825, in Start
    self.StartRunners(self.CreateRunners(FLAGS.job.split(','), FLAGS.logdir))
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1571, in CreateRunners
    trial)
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1524, in _CreateRunner
    return self.Trainer(cfg, *common_args)
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 405, in __init__
    self._model.ConstructFPropBPropGraph()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 1222, in ConstructFPropBPropGraph
    self._task.BProp()
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 564, in BProp
    self._BPropForVariables(self.vars)
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 595, in _BPropForVariables
    gradient_adjuster=self.AdjustGradients)
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/core/learner.py", line 173, in Apply
    p.gate_gradients)
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/core/optimizer.py", line 47, in ComputeGradients
    return py_utils.ComputeGradients(loss, vmap, *args, **kwargs)
  File "/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py", line 1915, in ComputeGradients
    assert filtered_vmap is not None
AssertionError`

**Comment by jonathanasdf** [comment]
The output from ComputeLoss is (metrics, per_example_tensors) where per_example_tensors is only used if you override ProcessFPropResults.

metrics['loss'] is the actual loss used for backprop.

In your case you have a constant loss which doesn't connect back to any variables

```
metrics = {
        'loss': (10.0, 20.0),
}
```
You should replace that with
```
metrics = {
        'loss': (tf.reduce_sum(loss), loss_weight),
}
```
where loss_weight is usually batch_size or sum over batch of sequence lengths, used to do averaging across devices when the input batch is split across multiple compute devices.
