### ISSUE TITLE
libcudart.so.11.0 error with `import lingvo.core.layers`

### ISSUE THREAD

**Issue by wq2012** [tensorflow/lingvo#282]
When I try to run `import lingvo.core.layers`, I get these errors:

```
Running tests in ./cumulative_statistics_layer_test.py
2022-03-21 13:15:03.805547: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/mesa-diverted/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/mesa:/usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/gallium-pipe
2022-03-21 13:15:03.805585: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/usr/local/google/home/quanw/Code/github/forks/speaker-id/lingvo/./cumulative_statistics_layer_test.py", line 9, in <module>
    import cumulative_statistics_layer
  File "/usr/local/google/home/quanw/Code/github/forks/speaker-id/lingvo/cumulative_statistics_layer.py", line 6, in <module>
    from lingvo.core import layers as lingvo_layers
  File "/usr/local/google/home/quanw/.local/lib/python3.9/site-packages/lingvo/core/layers.py", line 26, in <module>
    from lingvo.core import bn_layers
  File "/usr/local/google/home/quanw/.local/lib/python3.9/site-packages/lingvo/core/bn_layers.py", line 21, in <module>
    from lingvo.core import summary_utils
  File "/usr/local/google/home/quanw/.local/lib/python3.9/site-packages/lingvo/core/summary_utils.py", line 21, in <module>
    from lingvo.core import base_input_generator
  File "/usr/local/google/home/quanw/.local/lib/python3.9/site-packages/lingvo/core/base_input_generator.py", line 48, in <module>
    from lingvo.core import tokenizers
  File "/usr/local/google/home/quanw/.local/lib/python3.9/site-packages/lingvo/core/tokenizers.py", line 24, in <module>
    import tensorflow_text as tf_text
ModuleNotFoundError: No module named 'tensorflow_text'
```

Here is an example failure from our CI: https://github.com/wq2012/speaker-id/runs/5632341139?check_suite_focus=true

Is there any dependencies that we missed in the CI?

**Comment by wq2012** [comment]
Ye told me I just need `pip install tensorflow-text`.

**Comment by entrpn** [comment]
I tried running the [colab](https://colab.research.google.com/github/tensorflow/lingvo/blob/master/codelabs/introduction.ipynb) and ran into this issue. Just installing `tensorflow-text` won't work because the latest requires TensorFlow 2.9.

I had to install:

`tensorflow-text==2.7.3`

Then I got tensorflow probability error and had to install:

`tensorflow-probability==0.15.0`
