### ISSUE TITLE
cannot import name "hyperparams_pb2

### ISSUE THREAD

**Issue by WenTao0025** [tensorflow/lingvo#318]
python3 -m lingvo.trainer --run_locally=cpu --mode=sync --model=mnist.LeNet5 --logdir=/tmp/mnist/log
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/lingvo/lingvo/trainer.py", line 34, in <module>
    from lingvo import base_trial
  File "/tmp/lingvo/lingvo/base_trial.py", line 19, in <module>
    from lingvo.core import hyperparams
  File "/tmp/lingvo/lingvo/core/hyperparams.py", line 45, in <module>
    from lingvo.core import hyperparams_pb2
ImportError: cannot import name 'hyperparams_pb2' from 'lingvo.core' (/tmp/lingvo/lingvo/core/__init__.py)

**Comment by MrsButterfly** [comment]
I have this problem too.
