### ISSUE TITLE
Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by iamxiaoyubei** [tensorflow/lingvo#73]
I have successfully build trainer:
```
root@d4bff1951ef0:/tmp/lingvo# bazel build -c opt //lingvo:trainer
Starting local Bazel server and connecting to it...
INFO: Analysed target //lingvo:trainer (37 packages loaded, 4708 targets configured).
INFO: Found 1 target...
Target //lingvo:trainer up-to-date:
  bazel-bin/lingvo/trainer
INFO: Elapsed time: 4.297s, Critical Path: 0.19s
INFO: 1 process: 1 processwrapper-sandbox.
INFO: Build completed successfully, 5 total actions
```
and then I want to train with one gpu.

> My GPU infos:
> GeForce RTX 2070 8GB

But I got the following error infos:
```
2019-04-26 05:34:50.326859: I lingvo/core/ops/record_yielder.cc:341] Epoch 1 /tmp/librispeech/train/train.tfrecords-*
2019-04-26 05:36:05.261884: I lingvo/core/ops/record_batcher.cc:344] 75 total seconds passed. Total records yielded: 1. Total records skipped: 0
2019-04-26 05:36:15.802940: I tensorflow/stream_executor/platform/default/dso_loader.cc:43] Successfully opened dynamic library libcudnn.so.7
2019-04-26 05:36:26.895189: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-04-26 05:36:27.121682: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-04-26 05:36:27.306301: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-04-26 05:36:27.355048: W ./tensorflow/stream_executor/stream.h:1988] attempting to perform DNN operation using StreamExecutor without DNN support
2019-04-26 05:36:43.990367: I lingvo/core/ops/record_yielder.cc:313] 0x7f486bfdcf60Basic record yielder exit
......
I0426 05:36:57.030641 139959305754368 trainer.py:270] Save checkpoint done: /tmp/librispeech/Wpm/log/train/ckpt-00000000
2019-04-26 05:36:57.065397: I tensorflow/stream_executor/stream.cc:1852] [stream=0x6fa0670,impl=0x6fa0710] did not wait for [stream=0x6f9ffd0,impl=0x6fa0070]
2019-04-26 05:36:57.070022: I tensorflow/stream_executor/stream.cc:1852] [stream=0x6fa0670,impl=0x6fa0710] did not wait for [stream=0x6f9ffd0,impl=0x6fa0070]
2019-04-26 05:36:57.070450: I tensorflow/stream_executor/stream.cc:4800] [stream=0x6fa0670,impl=0x6fa0710] did not memcpy host-to-device; source: 0x7f4afbba5740
2019-04-26 05:36:57.070564: F tensorflow/core/common_runtime/gpu/gpu_util.cc:339] CPU->GPU Memcpy failed
Aborted (core dumped)
```
I found this issue [https://github.com/tensorflow/tensorflow/issues/24496](https://github.com/tensorflow/tensorflow/issues/24496), and set allow_growth to "True" in lingvo/core/py_utils.py line 394.

```
session_config.gpu_options.allow_growth = True
```

(I don't know whether I modify the right place because it is hard for me to find where are the corresponding parameters).  But it still can't solve my problem.

I think it may be caused by my poor GPU memory. So, I want to reduce the batch size to reduce the use of GPU memory. But I can't find where to modify batch size in codes. Could you please help me? Thanks a lot.

It is the details:
```
I0426 05:34:40.309401 139959226857216 base_runner.py:115] step:     0
I0426 05:34:40.994631 139959305754368 trainer.py:371] Steps/second: 0.000000, Examples/second: 0.000000
I0426 05:34:41.019921 139959305754368 trainer.py:268] Save checkpoint
2019-04-26 05:34:42.855256: W tensorflow/core/framework/allocator.cc:122] Allocation of 200638464 exceeds 10% of system memory.
2019-04-26 05:34:44.004477: W tensorflow/core/framework/allocator.cc:122] Allocation of 200638464 exceeds 10% of system memory.
2019-04-26 05:34:49.756821: I tensorflow/stream_executor/platform/default/dso_loader.cc:43] Successfully opened dynamic library libcublas.so.10.0
2019-04-26 05:34:50.238197: I ./lingvo/core/ops/input_common.h:68] Create RecordProcessor
2019-04-26 05:34:50.325285: I lingvo/core/ops/input_common.cc:30] Input source weights are empty, fall back to legacy behavior.
2019-04-26 05:34:50.325678: I lingvo/core/ops/record_yielder.cc:288] 0x7f486bfdcf60 Record yielder start
2019-04-26 05:34:50.325694: I lingvo/core/ops/record_yielder.cc:290] Randomly seed RecordYielder.
2019-04-26 05:34:50.326849: I ./lingvo/core/ops/input_common.h:73] Create batcher
2019-04-26 05:34:50.326859: I lingvo/core/ops/record_yielder.cc:341] Epoch 1 /tmp/librispeech/train/train.tfrecords-*
2019-04-26 05:36:05.261884: I lingvo/core/ops/record_batcher.cc:344] 75 total seconds passed. Total records yielded: 1. Total records skipped: 0
2019-04-26 05:36:15.802940: I tensorflow/stream_executor/platform/default/dso_loader.cc:43] Successfully opened dynamic library libcudnn.so.7
2019-04-26 05:36:26.895189: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-04-26 05:36:27.121682: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-04-26 05:36:27.306301: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-04-26 05:36:27.355048: W ./tensorflow/stream_executor/stream.h:1988] attempting to perform DNN operation using StreamExecutor without DNN support
2019-04-26 05:36:43.990367: I lingvo/core/ops/record_yielder.cc:313] 0x7f486bfdcf60Basic record yielder exit
I0426 05:36:45.892488 139959226857216 base_runner.py:236] trainer done (fatal error).
I0426 05:36:45.903496 139959226857216 base_runner.py:115] trainer exception: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node fprop/librispeech/tower_0_0/enc/conv_L0/convolution (defined at tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py:576) ]]
	 [[gradients/fprop/librispeech/tower_0_0/dec/embedding_lookup_grad/GatherV2_3_G308]]

Errors may have originated from an input operation.
Input Source operations connected to node fprop/librispeech/tower_0_0/enc/conv_L0/convolution:
 fprop/librispeech/tower_0_0/enc/mul (defined at tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py:2481)	
 fprop/librispeech/Identity_23 (defined at tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py:1313)

Original stack trace for u'fprop/librispeech/tower_0_0/enc/conv_L0/convolution':
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1557, in <module>
    tf.app.run(main)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1553, in main
    RunnerManager(FLAGS.model).Start()
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1546, in Start
    self.StartRunners(self.CreateRunners(FLAGS.job.split(','), FLAGS.logdir))
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1314, in CreateRunners
    trial)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1277, in _CreateRunner
    return self.Trainer(cfg, *common_args)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 386, in __init__
    self._model.ConstructFPropBPropGraph()
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 1235, in ConstructFPropBPropGraph
    self._task.FPropDefaultTheta()
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 477, in FPropDefaultTheta
    return self.FProp(self.theta, input_batch)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 394, in FProp
    metrics, per_example = self._FPropSplitInputBatch(theta, input_batch)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 440, in _FPropSplitInputBatch
    metrics, per_example = self.FPropTower(theta_local, batch)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 363, in FPropTower
    predicted = self.ComputePredictions(theta, input_batch)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/tasks/asr/model.py", line 124, in ComputePredictions
    encoder_outputs = self._FrontendAndEncoderFProp(theta, input_batch_src)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/tasks/asr/model.py", line 156, in _FrontendAndEncoderFProp
    return self.encoder.FProp(theta.encoder, input_batch_src)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/tasks/asr/encoder.py", line 333, in FProp
    out_padding)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 485, in FProp
    out = self._Compute(theta, inputs, paddings, conv_padding)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 515, in _Compute
    out = self._ApplyConv(theta, inputs, bn_padding_expanded)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 416, in _ApplyConv
    out = ComputeRawConvolution(filter_w)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 407, in ComputeRawConvolution
    padding_algorithm=padding_algorithm)
  File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 576, in _EvaluateConvKernel
    padding=padding_algorithm)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 894, in convolution
    name=name)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 971, in convolution_internal
    name=name)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3598, in create_op
    op_def=op_def)
  File "usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1994, in __init__
    self._traceback = tf_stack.extract_stack()


E0426 05:36:45.934931 139959226857216 base_runner.py:243] Traceback (most recent call last):
E0426 05:36:45.935090 139959226857216 base_runner.py:243]   File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/base_runner.py", line 196, in _RunLoop
E0426 05:36:45.935159 139959226857216 base_runner.py:243]     loop_func(*loop_args)
E0426 05:36:45.935215 139959226857216 base_runner.py:243]   File "/tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 508, in _Loop
E0426 05:36:45.935441 139959226857216 base_runner.py:243]     model_task.per_example_tensors,
E0426 05:36:45.935498 139959226857216 base_runner.py:243]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 948, in run
E0426 05:36:45.935554 139959226857216 base_runner.py:243]     run_metadata_ptr)
E0426 05:36:45.935607 139959226857216 base_runner.py:243]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1171, in _run
E0426 05:36:45.935661 139959226857216 base_runner.py:243]     feed_dict_tensor, options, run_metadata)
E0426 05:36:45.935713 139959226857216 base_runner.py:243]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_run
E0426 05:36:45.935761 139959226857216 base_runner.py:243]     run_metadata)
E0426 05:36:45.935817 139959226857216 base_runner.py:243]   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1368, in _do_call
E0426 05:36:45.935863 139959226857216 base_runner.py:243]     raise type(e)(node_def, op, message)
E0426 05:36:45.935920 139959226857216 base_runner.py:243] UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
E0426 05:36:45.935975 139959226857216 base_runner.py:243] 	 [[node fprop/librispeech/tower_0_0/enc/conv_L0/convolution (defined at tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py:576) ]]
E0426 05:36:45.936033 139959226857216 base_runner.py:243] 	 [[gradients/fprop/librispeech/tower_0_0/dec/embedding_lookup_grad/GatherV2_3_G308]]
E0426 05:36:45.936084 139959226857216 base_runner.py:243] 
E0426 05:36:45.936136 139959226857216 base_runner.py:243] Errors may have originated from an input operation.
E0426 05:36:45.936187 139959226857216 base_runner.py:243] Input Source operations connected to node fprop/librispeech/tower_0_0/enc/conv_L0/convolution:
E0426 05:36:45.936237 139959226857216 base_runner.py:243]  fprop/librispeech/tower_0_0/enc/mul (defined at tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py:2481)	
E0426 05:36:45.936291 139959226857216 base_runner.py:243]  fprop/librispeech/Identity_23 (defined at tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/py_utils.py:1313)
E0426 05:36:45.936342 139959226857216 base_runner.py:243] 
E0426 05:36:45.936393 139959226857216 base_runner.py:243] Original stack trace for u'fprop/librispeech/tower_0_0/enc/conv_L0/convolution':
E0426 05:36:45.936444 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1557, in <module>
E0426 05:36:45.936492 139959226857216 base_runner.py:243]     tf.app.run(main)
E0426 05:36:45.936542 139959226857216 base_runner.py:243]   File "usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
E0426 05:36:45.936590 139959226857216 base_runner.py:243]     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
E0426 05:36:45.936642 139959226857216 base_runner.py:243]   File "usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
E0426 05:36:45.936691 139959226857216 base_runner.py:243]     _run_main(main, args)
E0426 05:36:45.936743 139959226857216 base_runner.py:243]   File "usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
E0426 05:36:45.936791 139959226857216 base_runner.py:243]     sys.exit(main(argv))
E0426 05:36:45.936841 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1553, in main
E0426 05:36:45.936891 139959226857216 base_runner.py:243]     RunnerManager(FLAGS.model).Start()
E0426 05:36:45.936939 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1546, in Start
E0426 05:36:45.936990 139959226857216 base_runner.py:243]     self.StartRunners(self.CreateRunners(FLAGS.job.split(','), FLAGS.logdir))
E0426 05:36:45.937038 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1314, in CreateRunners
E0426 05:36:45.937088 139959226857216 base_runner.py:243]     trial)
E0426 05:36:45.937138 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 1277, in _CreateRunner
E0426 05:36:45.937187 139959226857216 base_runner.py:243]     return self.Trainer(cfg, *common_args)
E0426 05:36:45.937237 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/trainer.py", line 386, in __init__
E0426 05:36:45.937285 139959226857216 base_runner.py:243]     self._model.ConstructFPropBPropGraph()
E0426 05:36:45.937335 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 1235, in ConstructFPropBPropGraph
E0426 05:36:45.937383 139959226857216 base_runner.py:243]     self._task.FPropDefaultTheta()
E0426 05:36:45.937434 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 477, in FPropDefaultTheta
E0426 05:36:45.937490 139959226857216 base_runner.py:243]     return self.FProp(self.theta, input_batch)
E0426 05:36:45.937540 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 394, in FProp
E0426 05:36:45.937588 139959226857216 base_runner.py:243]     metrics, per_example = self._FPropSplitInputBatch(theta, input_batch)
E0426 05:36:45.937638 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 440, in _FPropSplitInputBatch
E0426 05:36:45.937689 139959226857216 base_runner.py:243]     metrics, per_example = self.FPropTower(theta_local, batch)
E0426 05:36:45.937736 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/base_model.py", line 363, in FPropTower
E0426 05:36:45.937787 139959226857216 base_runner.py:243]     predicted = self.ComputePredictions(theta, input_batch)
E0426 05:36:45.937835 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/tasks/asr/model.py", line 124, in ComputePredictions
E0426 05:36:45.937886 139959226857216 base_runner.py:243]     encoder_outputs = self._FrontendAndEncoderFProp(theta, input_batch_src)
E0426 05:36:45.937937 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/tasks/asr/model.py", line 156, in _FrontendAndEncoderFProp
E0426 05:36:45.937984 139959226857216 base_runner.py:243]     return self.encoder.FProp(theta.encoder, input_batch_src)
E0426 05:36:45.938035 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/tasks/asr/encoder.py", line 333, in FProp
E0426 05:36:45.938085 139959226857216 base_runner.py:243]     out_padding)
E0426 05:36:45.938134 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 485, in FProp
E0426 05:36:45.938184 139959226857216 base_runner.py:243]     out = self._Compute(theta, inputs, paddings, conv_padding)
E0426 05:36:45.938231 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 515, in _Compute
E0426 05:36:45.938282 139959226857216 base_runner.py:243]     out = self._ApplyConv(theta, inputs, bn_padding_expanded)
E0426 05:36:45.938330 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 416, in _ApplyConv
E0426 05:36:45.938374 139959226857216 base_runner.py:243]     out = ComputeRawConvolution(filter_w)
E0426 05:36:45.938416 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 407, in ComputeRawConvolution
E0426 05:36:45.938456 139959226857216 base_runner.py:243]     padding_algorithm=padding_algorithm)
E0426 05:36:45.938496 139959226857216 base_runner.py:243]   File "tmp/lingvo/bazel-bin/lingvo/trainer.runfiles/__main__/lingvo/core/layers.py", line 576, in _EvaluateConvKernel
E0426 05:36:45.938535 139959226857216 base_runner.py:243]     padding=padding_algorithm)
E0426 05:36:45.938587 139959226857216 base_runner.py:243]   File "usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 894, in convolution
E0426 05:36:45.938632 139959226857216 base_runner.py:243]     name=name)
E0426 05:36:45.938674 139959226857216 base_runner.py:243]   File "usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 971, in convolution_internal
E0426 05:36:45.938719 139959226857216 base_runner.py:243]     name=name)
E0426 05:36:45.938760 139959226857216 base_runner.py:243]   File "usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
E0426 05:36:45.938802 139959226857216 base_runner.py:243]     data_format=data_format, dilations=dilations, name=name)
E0426 05:36:45.938844 139959226857216 base_runner.py:243]   File "usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
E0426 05:36:45.938886 139959226857216 base_runner.py:243]     op_def=op_def)
E0426 05:36:45.938930 139959226857216 base_runner.py:243]   File "usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
E0426 05:36:45.938975 139959226857216 base_runner.py:243]     return func(*args, **kwargs)
E0426 05:36:45.939023 139959226857216 base_runner.py:243]   File "usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3598, in create_op
E0426 05:36:45.939069 139959226857216 base_runner.py:243]     op_def=op_def)
E0426 05:36:45.939116 139959226857216 base_runner.py:243]   File "usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1994, in __init__
E0426 05:36:45.939160 139959226857216 base_runner.py:243]     self._traceback = tf_stack.extract_stack()
E0426 05:36:45.939203 139959226857216 base_runner.py:243] 
E0426 05:36:45.939245 139959226857216 base_runner.py:243] 
W0426 05:36:56.804146 139959305754368 meta_graph.py:447] Issue encountered when serializing __batch_norm_update_dict.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'dict' object has no attribute 'name'
W0426 05:36:56.804761 139959305754368 meta_graph.py:447] Issue encountered when serializing __model_split_id_stack.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'list' object has no attribute 'name'
I0426 05:36:57.030641 139959305754368 trainer.py:270] Save checkpoint done: /tmp/librispeech/Wpm/log/train/ckpt-00000000
2019-04-26 05:36:57.065397: I tensorflow/stream_executor/stream.cc:1852] [stream=0x6fa0670,impl=0x6fa0710] did not wait for [stream=0x6f9ffd0,impl=0x6fa0070]
2019-04-26 05:36:57.070022: I tensorflow/stream_executor/stream.cc:1852] [stream=0x6fa0670,impl=0x6fa0710] did not wait for [stream=0x6f9ffd0,impl=0x6fa0070]
2019-04-26 05:36:57.070450: I tensorflow/stream_executor/stream.cc:4800] [stream=0x6fa0670,impl=0x6fa0710] did not memcpy host-to-device; source: 0x7f4afbba5740
2019-04-26 05:36:57.070564: F tensorflow/core/common_runtime/gpu/gpu_util.cc:339] CPU->GPU Memcpy failed
Aborted (core dumped)
```

**Comment by jonathanasdf** [comment]
Batch size for asr.librispeech is here https://github.com/tensorflow/lingvo/blob/405dd4789324e7af8607771485953ed25f4d45ac/lingvo/tasks/asr/params/librispeech.py#L65
