### ISSUE TITLE
What should I feed in ASR inference?

### ISSUE THREAD

**Issue by iamxiaoyubei** [tensorflow/lingvo#78]
I modify the model inference part in "/codelabs/introduction.ipynb" to inference ASR task.

I have tried many variables to feed. However, none of them are correct.

When I feed waveform, it occurs:
```
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
<ipython-input-13-533e43df44a2> in <module>()
     24 inference_graph = inference_graph_exporter.InferenceGraphExporter.Export(params)
     25 pred = predictor.Predictor(inference_graph, checkpoint=checkpoint, device_type='cpu')
---> 26 hyps, src_frames, en_frames, scores = pred.Run(['hypotheses', 'src_frames', 'encoder_frames', 'scores'], wav=wav_file)
     27 print(hyps)
     28 print(src_frames)

/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/ipython_kernel.runfiles/__main__/lingvo/core/predictor.py in Run(self, fetch_keys, **kwargs)
    206         report_tensor_allocations_upon_oom=False)
    207     return self._RunWithValidSession(
--> 208         tf.Session.run, fetches, feed_dict=feeds, options=run_options)
    209 
    210 

/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/ipython_kernel.runfiles/__main__/lingvo/core/retry.py in wrapper(*args, **kwargs)
     48       for retries in itertools.count(0):
     49         try:
---> 50           return func(*args, **kwargs)
     51         except retry_value as e:
     52           if retries >= max_retries:

/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/ipython_kernel.runfiles/__main__/lingvo/core/predictor.py in _RunWithValidSession(self, fn, *args, **kwargs)
    158     sess_id = self._cur_sess_id
    159     try:
--> 160       return fn(self._sess, *args, **kwargs)
    161     except py_utils.transient_tf_errors:
    162       # self._sess is invalid, most likely due to the worker being preempted.

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    946     try:
    947       result = self._run(None, fetches, feed_dict, options_ptr,
--> 948                          run_metadata_ptr)
    949       if run_metadata:
    950         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1169     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1170       results = self._do_run(handle, final_targets, final_fetches,
-> 1171                              feed_dict_tensor, options, run_metadata)
   1172     else:
   1173       results = []

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1346     if handle is None:
   1347       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1348                            run_metadata)
   1349     else:
   1350       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1366           pass
   1367       message = error_interpolation.interpolate(message, self._graph)
-> 1368       raise type(e)(node_def, op, message)
   1369 
   1370   def _extend_graph(self):

InternalError: Unable to get element as bytes.
```

When I feed tensor of waveform, it occurs:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-1a9314d06d8c> in <module>()
     24 inference_graph = inference_graph_exporter.InferenceGraphExporter.Export(params)
     25 pred = predictor.Predictor(inference_graph, checkpoint=checkpoint, device_type='cpu')
---> 26 hyps, src_frames, en_frames, scores = pred.Run(['hypotheses', 'src_frames', 'encoder_frames', 'scores'], wav=wav_tensor)
     27 print(hyps)
     28 print(src_frames)

/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/ipython_kernel.runfiles/__main__/lingvo/core/predictor.py in Run(self, fetch_keys, **kwargs)
    206         report_tensor_allocations_upon_oom=False)
    207     return self._RunWithValidSession(
--> 208         tf.Session.run, fetches, feed_dict=feeds, options=run_options)
    209 
    210 

/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/ipython_kernel.runfiles/__main__/lingvo/core/retry.py in wrapper(*args, **kwargs)
     48       for retries in itertools.count(0):
     49         try:
---> 50           return func(*args, **kwargs)
     51         except retry_value as e:
     52           if retries >= max_retries:

/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/ipython_kernel.runfiles/__main__/lingvo/core/predictor.py in _RunWithValidSession(self, fn, *args, **kwargs)
    158     sess_id = self._cur_sess_id
    159     try:
--> 160       return fn(self._sess, *args, **kwargs)
    161     except py_utils.transient_tf_errors:
    162       # self._sess is invalid, most likely due to the worker being preempted.

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    946     try:
    947       result = self._run(None, fetches, feed_dict, options_ptr,
--> 948                          run_metadata_ptr)
    949       if run_metadata:
    950         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1120                             'For reference, the tensor object was ' +
   1121                             str(feed_val) + ' which was passed to the '
-> 1122                             'feed with key ' + str(feed) + '.')
   1123 
   1124           subfeed_dtype = subfeed_t.dtype.as_numpy_dtype

TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles. For reference, the tensor object was Tensor("Const_2:0", shape=(60080,), dtype=int16) which was passed to the feed with key inference/default/wav:0.
```

When I feed the filename of wav, it occurs:
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-15-17fbc70adb3e> in <module>()
     24 inference_graph = inference_graph_exporter.InferenceGraphExporter.Export(params)
     25 pred = predictor.Predictor(inference_graph, checkpoint=checkpoint, device_type='cpu')
---> 26 hyps, src_frames, en_frames, scores = pred.Run(['hypotheses', 'src_frames', 'encoder_frames', 'scores'], wav='/tmp/librispeech/arctic_a0002.wav')
     27 print(hyps)
     28 print(src_frames)

/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/ipython_kernel.runfiles/__main__/lingvo/core/predictor.py in Run(self, fetch_keys, **kwargs)
    206         report_tensor_allocations_upon_oom=False)
    207     return self._RunWithValidSession(
--> 208         tf.Session.run, fetches, feed_dict=feeds, options=run_options)
    209 
    210 

/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/ipython_kernel.runfiles/__main__/lingvo/core/retry.py in wrapper(*args, **kwargs)
     48       for retries in itertools.count(0):
     49         try:
---> 50           return func(*args, **kwargs)
     51         except retry_value as e:
     52           if retries >= max_retries:

/root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/execroot/__main__/bazel-out/k8-opt/bin/lingvo/ipython_kernel.runfiles/__main__/lingvo/core/predictor.py in _RunWithValidSession(self, fn, *args, **kwargs)
    158     sess_id = self._cur_sess_id
    159     try:
--> 160       return fn(self._sess, *args, **kwargs)
    161     except py_utils.transient_tf_errors:
    162       # self._sess is invalid, most likely due to the worker being preempted.

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    946     try:
    947       result = self._run(None, fetches, feed_dict, options_ptr,
--> 948                          run_metadata_ptr)
    949       if run_metadata:
    950         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1169     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1170       results = self._do_run(handle, final_targets, final_fetches,
-> 1171                              feed_dict_tensor, options, run_metadata)
   1172     else:
   1173       results = []

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1346     if handle is None:
   1347       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1348                            run_metadata)
   1349     else:
   1350       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1366           pass
   1367       message = error_interpolation.interpolate(message, self._graph)
-> 1368       raise type(e)(node_def, op, message)
   1369 
   1370   def _extend_graph(self):

InvalidArgumentError: Header mismatch: Expected RIFF but found /tmp
	 [[node inference/default/DecodeWav (defined at lingvo/core/predictor.py:93) ]]

Original stack trace for u'inference/default/DecodeWav':
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 499, in start
    self.io_loop.start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 1073, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2714, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2818, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-17fbc70adb3e>", line 25, in <module>
    pred = predictor.Predictor(inference_graph, checkpoint=checkpoint, device_type='cpu')
  File "lingvo/core/predictor.py", line 93, in __init__
    tf.import_graph_def(inference_graph.graph_def, name="")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 443, in import_graph_def
    _ProcessNewOps(graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 236, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3733, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3623, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1994, in __init__
    self._traceback = tf_stack.extract_stack()
```

I also tried a list of them separately. However, none of them are correct. I have seen inference function in /tasks/asr/model.py and DecodeWav function in /tools/audio_lib.py. So I tried the above ways.

Could you please tell me what should I feed? I extremely expect you to provide me with the inference code of ASR task. Thank you so much!!

**Comment by iamxiaoyubei** [comment]
It is the codes to read waveform:
```
from scipy.io import wavfile
import tensorflow as tf
sample_rate, wav_file = wavfile.read('/tmp/librispeech/arctic_a0002.wav')
print(wav_file)
wav_tensor = tf.convert_to_tensor(wav_file)
```

**Comment by iamxiaoyubei** [comment]
It is the three feed ways:
```hyps, src_frames, en_frames, scores = pred.Run(['hypotheses', 'src_frames', 'encoder_frames', 'scores'], wav='/tmp/librispeech/arctic_a0002.wav')
```
```
hyps, src_frames, en_frames, scores = pred.Run(['hypotheses', 'src_frames', 'encoder_frames', 'scores'], wav=wav_file)
```
```
hyps, src_frames, en_frames, scores = pred.Run(['hypotheses', 'src_frames', 'encoder_frames', 'scores'], wav=wav_tensor)
```
